### ISSUE TITLE
Broken download links at README.md

### ISSUE THREAD

**Issue by terremoth** [halpz/re3#1]
Broken download links at README.md

links like:
https://nightly.link/GTAmodding/re3/workflows/re3_msvc_amd64/master/re3_Release_win-amd64-librw_d3d9-oal.zip  
https://nightly.link/GTAmodding/re3/workflows/re3_msvc_amd64/master/re3_Release_win-amd64-librw_gl3_glfw-oal.zip

**Comment by Yilmaz4** [comment]
They were removed from servers due to DMCA takedown. Here you can download from here: https://www.gamepressure.com/download.asp?ID=77273
